# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_interface.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1524, 868)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 50, 1024, 768))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 25px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(600, 70, 321, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1230, 60, 30, 30))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"}")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/素材库/exit.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(250, 130, 1024, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.recognizers = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.recognizers.setFont(font)
        self.recognizers.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:focus{\n"
"    color: rgb(186, 186, 186);\n"
"}")
        self.recognizers.setObjectName("recognizers")
        self.horizontalLayout.addWidget(self.recognizers)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.diagnosers = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.diagnosers.setFont(font)
        self.diagnosers.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:focus{\n"
"    color: rgb(186, 186, 186);\n"
"}")
        self.diagnosers.setObjectName("diagnosers")
        self.horizontalLayout.addWidget(self.diagnosers)
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.treatments = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.treatments.setFont(font)
        self.treatments.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:focus{\n"
"    color: rgb(186, 186, 186);\n"
"}")
        self.treatments.setObjectName("treatments")
        self.horizontalLayout.addWidget(self.treatments)
        self.recognize_widget = QtWidgets.QWidget(self.centralwidget)
        self.recognize_widget.setGeometry(QtCore.QRect(250, 180, 1024, 621))
        self.recognize_widget.setObjectName("recognize_widget")
        self.rcg_videoshow = QtWidgets.QLabel(self.recognize_widget)
        self.rcg_videoshow.setGeometry(QtCore.QRect(40, 30, 640, 480))
        self.rcg_videoshow.setStyleSheet("background-color: rgb(234, 234, 234);\n"
"background-color: rgb(211, 211, 211);\n"
"border-radius: 10px;")
        self.rcg_videoshow.setText("")
        self.rcg_videoshow.setObjectName("rcg_videoshow")
        self.rcg_browser = QtWidgets.QTextBrowser(self.recognize_widget)
        self.rcg_browser.setGeometry(QtCore.QRect(40, 520, 640, 91))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.rcg_browser.setFont(font)
        self.rcg_browser.setStyleSheet("border-radius: 10px;\n"
"border: 1px solid rgb(0, 0, 0);")
        self.rcg_browser.setCursorWidth(1)
        self.rcg_browser.setObjectName("rcg_browser")
        self.rcg_start = QtWidgets.QPushButton(self.recognize_widget)
        self.rcg_start.setGeometry(QtCore.QRect(760, 80, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.rcg_start.setFont(font)
        self.rcg_start.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(222, 222, 222);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-top:7px;\n"
"    padding-left:5px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/素材库/camera-change.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rcg_start.setIcon(icon1)
        self.rcg_start.setIconSize(QtCore.QSize(30, 30))
        self.rcg_start.setObjectName("rcg_start")
        self.rcg_stop = QtWidgets.QPushButton(self.recognize_widget)
        self.rcg_stop.setGeometry(QtCore.QRect(760, 150, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.rcg_stop.setFont(font)
        self.rcg_stop.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(222, 222, 222);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-top:7px;\n"
"    padding-left:5px;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/素材库/camera.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rcg_stop.setIcon(icon2)
        self.rcg_stop.setIconSize(QtCore.QSize(30, 30))
        self.rcg_stop.setObjectName("rcg_stop")
        self.rcg_recognize = QtWidgets.QPushButton(self.recognize_widget)
        self.rcg_recognize.setGeometry(QtCore.QRect(760, 220, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.rcg_recognize.setFont(font)
        self.rcg_recognize.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(222, 222, 222);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-top:7px;\n"
"    padding-left:5px;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/素材库/face-recognition.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rcg_recognize.setIcon(icon3)
        self.rcg_recognize.setIconSize(QtCore.QSize(30, 30))
        self.rcg_recognize.setObjectName("rcg_recognize")
        self.rcg_name = QtWidgets.QLineEdit(self.recognize_widget)
        self.rcg_name.setGeometry(QtCore.QRect(770, 290, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.rcg_name.setFont(font)
        self.rcg_name.setStyleSheet("border: none;\n"
"background-color: rgb(255, 255, 255,0);\n"
"border-bottom: 1px solid rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.rcg_name.setText("")
        self.rcg_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.rcg_name.setObjectName("rcg_name")
        self.rcg_save = QtWidgets.QPushButton(self.recognize_widget)
        self.rcg_save.setGeometry(QtCore.QRect(910, 290, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.rcg_save.setFont(font)
        self.rcg_save.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(222, 222, 222);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-top:7px;\n"
"    padding-left:5px;\n"
"}")
        self.rcg_save.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/素材库/save.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rcg_save.setIcon(icon4)
        self.rcg_save.setIconSize(QtCore.QSize(30, 30))
        self.rcg_save.setObjectName("rcg_save")
        self.rcg_tableWidget = QtWidgets.QTableWidget(self.recognize_widget)
        self.rcg_tableWidget.setGeometry(QtCore.QRect(750, 380, 211, 211))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rcg_tableWidget.setFont(font)
        self.rcg_tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rcg_tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rcg_tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.rcg_tableWidget.setRowCount(5)
        self.rcg_tableWidget.setObjectName("rcg_tableWidget")
        self.rcg_tableWidget.setColumnCount(1)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.rcg_tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.rcg_tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.rcg_tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.rcg_tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.rcg_tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.rcg_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.rcg_tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.rcg_tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.rcg_tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.rcg_tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.rcg_tableWidget.setItem(4, 0, item)
        self.diagnose_widget = QtWidgets.QWidget(self.centralwidget)
        self.diagnose_widget.setGeometry(QtCore.QRect(250, 180, 1024, 621))
        self.diagnose_widget.setObjectName("diagnose_widget")
        self.dag_videoshow = QtWidgets.QLabel(self.diagnose_widget)
        self.dag_videoshow.setGeometry(QtCore.QRect(40, 30, 640, 480))
        self.dag_videoshow.setStyleSheet("background-color: rgb(234, 234, 234);\n"
"background-color: rgb(211, 211, 211);\n"
"border-radius: 10px;")
        self.dag_videoshow.setText("")
        self.dag_videoshow.setObjectName("dag_videoshow")
        self.dag_browser = QtWidgets.QTextBrowser(self.diagnose_widget)
        self.dag_browser.setGeometry(QtCore.QRect(40, 520, 640, 91))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.dag_browser.setFont(font)
        self.dag_browser.setStyleSheet("border-radius: 10px;\n"
"border: 1px solid rgb(0, 0, 0);")
        self.dag_browser.setCursorWidth(1)
        self.dag_browser.setObjectName("dag_browser")
        self.dag_name = QtWidgets.QLineEdit(self.diagnose_widget)
        self.dag_name.setGeometry(QtCore.QRect(760, 40, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.dag_name.setFont(font)
        self.dag_name.setStyleSheet("border: none;\n"
"background-color: rgb(255, 255, 255,0);\n"
"border-bottom: 1px solid rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.dag_name.setText("")
        self.dag_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.dag_name.setObjectName("dag_name")
        self.dag_search = QtWidgets.QPushButton(self.diagnose_widget)
        self.dag_search.setGeometry(QtCore.QRect(910, 100, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.dag_search.setFont(font)
        self.dag_search.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(222, 222, 222);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-top:7px;\n"
"    padding-left:5px;\n"
"}")
        self.dag_search.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/素材库/search.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dag_search.setIcon(icon5)
        self.dag_search.setIconSize(QtCore.QSize(30, 30))
        self.dag_search.setObjectName("dag_search")
        self.dag_mechine = QtWidgets.QCheckBox(self.diagnose_widget)
        self.dag_mechine.setGeometry(QtCore.QRect(760, 220, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.dag_mechine.setFont(font)
        self.dag_mechine.setObjectName("dag_mechine")
        self.dag_painlevel = QtWidgets.QLineEdit(self.diagnose_widget)
        self.dag_painlevel.setGeometry(QtCore.QRect(860, 150, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dag_painlevel.setFont(font)
        self.dag_painlevel.setStyleSheet("border: none;\n"
"background-color: rgb(255, 255, 255,0);\n"
"border-bottom: 1px solid rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.dag_painlevel.setText("")
        self.dag_painlevel.setAlignment(QtCore.Qt.AlignCenter)
        self.dag_painlevel.setPlaceholderText("")
        self.dag_painlevel.setObjectName("dag_painlevel")
        self.label_3 = QtWidgets.QLabel(self.diagnose_widget)
        self.label_3.setGeometry(QtCore.QRect(760, 270, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.dag_treattime = QtWidgets.QLineEdit(self.diagnose_widget)
        self.dag_treattime.setGeometry(QtCore.QRect(880, 270, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.dag_treattime.setFont(font)
        self.dag_treattime.setStyleSheet("border: none;\n"
"background-color: rgb(255, 255, 255,0);\n"
"border-bottom: 1px solid rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.dag_treattime.setText("")
        self.dag_treattime.setAlignment(QtCore.Qt.AlignCenter)
        self.dag_treattime.setPlaceholderText("")
        self.dag_treattime.setObjectName("dag_treattime")
        self.label_4 = QtWidgets.QLabel(self.diagnose_widget)
        self.label_4.setGeometry(QtCore.QRect(930, 270, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.diagnose_widget)
        self.label_5.setGeometry(QtCore.QRect(760, 150, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.diagnose_widget)
        self.label_6.setGeometry(QtCore.QRect(760, 330, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.dag_drug1 = QtWidgets.QRadioButton(self.diagnose_widget)
        self.dag_drug1.setGeometry(QtCore.QRect(780, 370, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.dag_drug1.setFont(font)
        self.dag_drug1.setObjectName("dag_drug1")
        self.dag_drug2 = QtWidgets.QRadioButton(self.diagnose_widget)
        self.dag_drug2.setGeometry(QtCore.QRect(880, 370, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.dag_drug2.setFont(font)
        self.dag_drug2.setObjectName("dag_drug2")
        self.dag_drug3 = QtWidgets.QRadioButton(self.diagnose_widget)
        self.dag_drug3.setGeometry(QtCore.QRect(780, 410, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.dag_drug3.setFont(font)
        self.dag_drug3.setObjectName("dag_drug3")
        self.dag_drug4 = QtWidgets.QRadioButton(self.diagnose_widget)
        self.dag_drug4.setGeometry(QtCore.QRect(880, 410, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.dag_drug4.setFont(font)
        self.dag_drug4.setObjectName("dag_drug4")
        self.dag_remark = QtWidgets.QTextEdit(self.diagnose_widget)
        self.dag_remark.setGeometry(QtCore.QRect(750, 460, 251, 101))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.dag_remark.setFont(font)
        self.dag_remark.setObjectName("dag_remark")
        self.dag_reset = QtWidgets.QPushButton(self.diagnose_widget)
        self.dag_reset.setGeometry(QtCore.QRect(820, 570, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.dag_reset.setFont(font)
        self.dag_reset.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(222, 222, 222);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-top:7px;\n"
"    padding-left:5px;\n"
"}")
        self.dag_reset.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/素材库/reset.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dag_reset.setIcon(icon6)
        self.dag_reset.setIconSize(QtCore.QSize(30, 30))
        self.dag_reset.setObjectName("dag_reset")
        self.dag_submit = QtWidgets.QPushButton(self.diagnose_widget)
        self.dag_submit.setGeometry(QtCore.QRect(950, 570, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.dag_submit.setFont(font)
        self.dag_submit.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(222, 222, 222);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-top:7px;\n"
"    padding-left:5px;\n"
"}")
        self.dag_submit.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/素材库/upload.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dag_submit.setIcon(icon7)
        self.dag_submit.setIconSize(QtCore.QSize(30, 30))
        self.dag_submit.setObjectName("dag_submit")
        self.label_7 = QtWidgets.QLabel(self.diagnose_widget)
        self.label_7.setGeometry(QtCore.QRect(780, 570, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.diagnose_widget)
        self.label_8.setGeometry(QtCore.QRect(910, 570, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.frame = QtWidgets.QFrame(self.diagnose_widget)
        self.frame.setGeometry(QtCore.QRect(750, 100, 161, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.dag_male = QtWidgets.QRadioButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.dag_male.setFont(font)
        self.dag_male.setObjectName("dag_male")
        self.horizontalLayout_2.addWidget(self.dag_male)
        self.dag_female = QtWidgets.QRadioButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.dag_female.setFont(font)
        self.dag_female.setObjectName("dag_female")
        self.horizontalLayout_2.addWidget(self.dag_female)
        self.treatment_widget = QtWidgets.QWidget(self.centralwidget)
        self.treatment_widget.setGeometry(QtCore.QRect(250, 180, 1024, 621))
        self.treatment_widget.setObjectName("treatment_widget")
        self.label_11 = QtWidgets.QLabel(self.treatment_widget)
        self.label_11.setGeometry(QtCore.QRect(17, 310, 531, 286))
        self.label_11.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 25px;")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.treatment_widget)
        self.label_12.setGeometry(QtCore.QRect(555, 310, 441, 286))
        self.label_12.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 25px;")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_9 = QtWidgets.QLabel(self.treatment_widget)
        self.label_9.setGeometry(QtCore.QRect(17, 17, 981, 286))
        self.label_9.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 25px;")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_13 = QtWidgets.QLabel(self.treatment_widget)
        self.label_13.setGeometry(QtCore.QRect(440, 30, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(120, 120, 120);")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.trm_name = QtWidgets.QLineEdit(self.treatment_widget)
        self.trm_name.setGeometry(QtCore.QRect(290, 100, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.trm_name.setFont(font)
        self.trm_name.setStyleSheet("border: none;\n"
"background-color: rgb(255, 255, 255,0);\n"
"border-bottom: 1px solid rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.trm_name.setText("")
        self.trm_name.setAlignment(QtCore.Qt.AlignCenter)
        self.trm_name.setPlaceholderText("")
        self.trm_name.setObjectName("trm_name")
        self.label_14 = QtWidgets.QLabel(self.treatment_widget)
        self.label_14.setGeometry(QtCore.QRect(180, 100, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.trm_gender = QtWidgets.QLineEdit(self.treatment_widget)
        self.trm_gender.setGeometry(QtCore.QRect(500, 100, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.trm_gender.setFont(font)
        self.trm_gender.setStyleSheet("border: none;\n"
"background-color: rgb(255, 255, 255,0);\n"
"border-bottom: 1px solid rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.trm_gender.setText("")
        self.trm_gender.setAlignment(QtCore.Qt.AlignCenter)
        self.trm_gender.setPlaceholderText("")
        self.trm_gender.setObjectName("trm_gender")
        self.label_15 = QtWidgets.QLabel(self.treatment_widget)
        self.label_15.setGeometry(QtCore.QRect(440, 100, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.trm_painlevel = QtWidgets.QLineEdit(self.treatment_widget)
        self.trm_painlevel.setGeometry(QtCore.QRect(700, 100, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.trm_painlevel.setFont(font)
        self.trm_painlevel.setStyleSheet("border: none;\n"
"background-color: rgb(255, 255, 255,0);\n"
"border-bottom: 1px solid rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.trm_painlevel.setText("")
        self.trm_painlevel.setAlignment(QtCore.Qt.AlignCenter)
        self.trm_painlevel.setPlaceholderText("")
        self.trm_painlevel.setObjectName("trm_painlevel")
        self.label_16 = QtWidgets.QLabel(self.treatment_widget)
        self.label_16.setGeometry(QtCore.QRect(590, 100, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.treatment_widget)
        self.label_17.setGeometry(QtCore.QRect(180, 160, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.trm_mechine = QtWidgets.QLineEdit(self.treatment_widget)
        self.trm_mechine.setGeometry(QtCore.QRect(350, 160, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.trm_mechine.setFont(font)
        self.trm_mechine.setStyleSheet("border: none;\n"
"background-color: rgb(255, 255, 255,0);\n"
"border-bottom: 1px solid rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.trm_mechine.setText("")
        self.trm_mechine.setAlignment(QtCore.Qt.AlignCenter)
        self.trm_mechine.setPlaceholderText("")
        self.trm_mechine.setObjectName("trm_mechine")
        self.trm_treattime = QtWidgets.QLineEdit(self.treatment_widget)
        self.trm_treattime.setGeometry(QtCore.QRect(670, 160, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.trm_treattime.setFont(font)
        self.trm_treattime.setStyleSheet("border: none;\n"
"background-color: rgb(255, 255, 255,0);\n"
"border-bottom: 1px solid rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.trm_treattime.setText("")
        self.trm_treattime.setAlignment(QtCore.Qt.AlignCenter)
        self.trm_treattime.setPlaceholderText("")
        self.trm_treattime.setObjectName("trm_treattime")
        self.label_18 = QtWidgets.QLabel(self.treatment_widget)
        self.label_18.setGeometry(QtCore.QRect(520, 160, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.treatment_widget)
        self.label_19.setGeometry(QtCore.QRect(180, 220, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.trm_drug = QtWidgets.QLineEdit(self.treatment_widget)
        self.trm_drug.setGeometry(QtCore.QRect(280, 220, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.trm_drug.setFont(font)
        self.trm_drug.setStyleSheet("border: none;\n"
"background-color: rgb(255, 255, 255,0);\n"
"border-bottom: 1px solid rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.trm_drug.setText("")
        self.trm_drug.setAlignment(QtCore.Qt.AlignCenter)
        self.trm_drug.setPlaceholderText("")
        self.trm_drug.setObjectName("trm_drug")
        self.trm_remark = QtWidgets.QLineEdit(self.treatment_widget)
        self.trm_remark.setGeometry(QtCore.QRect(490, 220, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.trm_remark.setFont(font)
        self.trm_remark.setStyleSheet("border: none;\n"
"background-color: rgb(255, 255, 255,0);\n"
"border-bottom: 1px solid rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.trm_remark.setText("")
        self.trm_remark.setAlignment(QtCore.Qt.AlignCenter)
        self.trm_remark.setPlaceholderText("")
        self.trm_remark.setObjectName("trm_remark")
        self.label_20 = QtWidgets.QLabel(self.treatment_widget)
        self.label_20.setGeometry(QtCore.QRect(430, 220, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.trm_search = QtWidgets.QPushButton(self.treatment_widget)
        self.trm_search.setGeometry(QtCore.QRect(850, 240, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.trm_search.setFont(font)
        self.trm_search.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(222, 222, 222);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-top:7px;\n"
"    padding-left:5px;\n"
"}")
        self.trm_search.setIcon(icon5)
        self.trm_search.setIconSize(QtCore.QSize(30, 30))
        self.trm_search.setObjectName("trm_search")
        self.trm_browser = QtWidgets.QTextBrowser(self.treatment_widget)
        self.trm_browser.setGeometry(QtCore.QRect(580, 380, 391, 131))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.trm_browser.setFont(font)
        self.trm_browser.setStyleSheet("border-radius: 10px;\n"
"border: 1px solid rgb(0, 0, 0);")
        self.trm_browser.setCursorWidth(1)
        self.trm_browser.setObjectName("trm_browser")
        self.label_21 = QtWidgets.QLabel(self.treatment_widget)
        self.label_21.setGeometry(QtCore.QRect(710, 320, 127, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(120, 120, 120);")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.treatment_widget)
        self.label_22.setGeometry(QtCore.QRect(210, 320, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(120, 120, 120);")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.treatment_widget)
        self.label_23.setGeometry(QtCore.QRect(90, 360, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.line_3 = QtWidgets.QFrame(self.treatment_widget)
        self.line_3.setGeometry(QtCore.QRect(270, 370, 20, 201))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_24 = QtWidgets.QLabel(self.treatment_widget)
        self.label_24.setGeometry(QtCore.QRect(350, 360, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.treatment_widget)
        self.label_25.setGeometry(QtCore.QRect(30, 420, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.treatment_widget)
        self.label_26.setGeometry(QtCore.QRect(30, 490, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.trm_mechine_worktime = QtWidgets.QLineEdit(self.treatment_widget)
        self.trm_mechine_worktime.setGeometry(QtCore.QRect(140, 490, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.trm_mechine_worktime.setFont(font)
        self.trm_mechine_worktime.setStyleSheet("border: none;\n"
"background-color: rgb(255, 255, 255,0);\n"
"border-bottom: 1px solid rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.trm_mechine_worktime.setText("")
        self.trm_mechine_worktime.setAlignment(QtCore.Qt.AlignCenter)
        self.trm_mechine_worktime.setObjectName("trm_mechine_worktime")
        self.trm_mechine_workmode = QtWidgets.QComboBox(self.treatment_widget)
        self.trm_mechine_workmode.setGeometry(QtCore.QRect(140, 420, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.trm_mechine_workmode.setFont(font)
        self.trm_mechine_workmode.setObjectName("trm_mechine_workmode")
        self.trm_mechine_workmode.addItem("")
        self.trm_mechine_workmode.setItemText(0, "")
        self.trm_mechine_workmode.addItem("")
        self.trm_mechine_workmode.addItem("")
        self.trm_mechine_workmode.addItem("")
        self.label_27 = QtWidgets.QLabel(self.treatment_widget)
        self.label_27.setGeometry(QtCore.QRect(300, 410, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.trm_durg_use = QtWidgets.QComboBox(self.treatment_widget)
        self.trm_durg_use.setGeometry(QtCore.QRect(410, 410, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.trm_durg_use.setFont(font)
        self.trm_durg_use.setObjectName("trm_durg_use")
        self.trm_durg_use.addItem("")
        self.trm_durg_use.setItemText(0, "")
        self.trm_durg_use.addItem("")
        self.trm_durg_use.addItem("")
        self.trm_durg_use.addItem("")
        self.trm_durg_use.addItem("")
        self.trm_drug_speed = QtWidgets.QLineEdit(self.treatment_widget)
        self.trm_drug_speed.setGeometry(QtCore.QRect(410, 510, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.trm_drug_speed.setFont(font)
        self.trm_drug_speed.setStyleSheet("border: none;\n"
"background-color: rgb(255, 255, 255,0);\n"
"border-bottom: 1px solid rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.trm_drug_speed.setText("")
        self.trm_drug_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.trm_drug_speed.setObjectName("trm_drug_speed")
        self.label_28 = QtWidgets.QLabel(self.treatment_widget)
        self.label_28.setGeometry(QtCore.QRect(300, 510, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.treatment_widget)
        self.label_29.setGeometry(QtCore.QRect(300, 460, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.trm_drug_mass = QtWidgets.QLineEdit(self.treatment_widget)
        self.trm_drug_mass.setGeometry(QtCore.QRect(410, 460, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.trm_drug_mass.setFont(font)
        self.trm_drug_mass.setStyleSheet("border: none;\n"
"background-color: rgb(255, 255, 255,0);\n"
"border-bottom: 1px solid rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.trm_drug_mass.setText("")
        self.trm_drug_mass.setAlignment(QtCore.Qt.AlignCenter)
        self.trm_drug_mass.setObjectName("trm_drug_mass")
        self.trm_reset = QtWidgets.QPushButton(self.treatment_widget)
        self.trm_reset.setGeometry(QtCore.QRect(640, 530, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.trm_reset.setFont(font)
        self.trm_reset.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(222, 222, 222);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-top:7px;\n"
"    padding-left:5px;\n"
"}")
        self.trm_reset.setIcon(icon6)
        self.trm_reset.setIconSize(QtCore.QSize(30, 30))
        self.trm_reset.setObjectName("trm_reset")
        self.trm_start = QtWidgets.QPushButton(self.treatment_widget)
        self.trm_start.setGeometry(QtCore.QRect(820, 530, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.trm_start.setFont(font)
        self.trm_start.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(222, 222, 222);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-top:7px;\n"
"    padding-left:5px;\n"
"}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/素材库/lamp-switch.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.trm_start.setIcon(icon8)
        self.trm_start.setIconSize(QtCore.QSize(40, 40))
        self.trm_start.setObjectName("trm_start")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "智能疼痛管理系统"))
        self.recognizers.setText(_translate("MainWindow", "识别"))
        self.diagnosers.setText(_translate("MainWindow", "诊断"))
        self.treatments.setText(_translate("MainWindow", "治疗"))
        self.rcg_browser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:13pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt;\"><br /></p></body></html>"))
        self.rcg_browser.setPlaceholderText(_translate("MainWindow", "[操作提示]"))
        self.rcg_start.setText(_translate("MainWindow", "开始拍摄图像"))
        self.rcg_stop.setText(_translate("MainWindow", "停止拍摄图像"))
        self.rcg_recognize.setText(_translate("MainWindow", "疼痛表情识别"))
        self.rcg_name.setPlaceholderText(_translate("MainWindow", "患者姓名："))
        item = self.rcg_tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "No"))
        item = self.rcg_tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Weak"))
        item = self.rcg_tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", " Moderate"))
        item = self.rcg_tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Severe"))
        item = self.rcg_tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "准确率"))
        item = self.rcg_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "帧数"))
        __sortingEnabled = self.rcg_tableWidget.isSortingEnabled()
        self.rcg_tableWidget.setSortingEnabled(False)
        self.rcg_tableWidget.setSortingEnabled(__sortingEnabled)
        self.dag_browser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:13pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt;\"><br /></p></body></html>"))
        self.dag_browser.setPlaceholderText(_translate("MainWindow", "[操作提示]"))
        self.dag_name.setPlaceholderText(_translate("MainWindow", "患者姓名："))
        self.dag_mechine.setText(_translate("MainWindow", "启用按摩仪"))
        self.label_3.setText(_translate("MainWindow", "建议治疗时长："))
        self.label_4.setText(_translate("MainWindow", "分钟"))
        self.label_5.setText(_translate("MainWindow", "疼痛等级"))
        self.label_6.setText(_translate("MainWindow", "止痛剂选择："))
        self.dag_drug1.setText(_translate("MainWindow", "酮铬酸"))
        self.dag_drug2.setText(_translate("MainWindow", "氯诺昔康"))
        self.dag_drug3.setText(_translate("MainWindow", "保泰松"))
        self.dag_drug4.setText(_translate("MainWindow", "芬太尼"))
        self.dag_remark.setPlaceholderText(_translate("MainWindow", "备注："))
        self.label_7.setText(_translate("MainWindow", "重置"))
        self.label_8.setText(_translate("MainWindow", "提交"))
        self.dag_male.setText(_translate("MainWindow", "男"))
        self.dag_female.setText(_translate("MainWindow", "女"))
        self.label_13.setText(_translate("MainWindow", "患者信息"))
        self.label_14.setText(_translate("MainWindow", "患者姓名:"))
        self.label_15.setText(_translate("MainWindow", "性别:"))
        self.label_16.setText(_translate("MainWindow", "疼痛等级:"))
        self.label_17.setText(_translate("MainWindow", "是否启用按摩仪:"))
        self.label_18.setText(_translate("MainWindow", "推荐治疗时长:"))
        self.label_19.setText(_translate("MainWindow", "止痛药剂:"))
        self.label_20.setText(_translate("MainWindow", "备注:"))
        self.trm_search.setText(_translate("MainWindow", "查询"))
        self.trm_browser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:13pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt;\"><br /></p></body></html>"))
        self.trm_browser.setPlaceholderText(_translate("MainWindow", "[操作提示]"))
        self.label_21.setText(_translate("MainWindow", "仪器提示"))
        self.label_22.setText(_translate("MainWindow", "治疗设置"))
        self.label_23.setText(_translate("MainWindow", "按摩仪"))
        self.label_24.setText(_translate("MainWindow", "镇痛泵"))
        self.label_25.setText(_translate("MainWindow", "工作模式:"))
        self.label_26.setText(_translate("MainWindow", "治疗时长:"))
        self.trm_mechine_worktime.setPlaceholderText(_translate("MainWindow", "分钟"))
        self.trm_mechine_workmode.setItemText(1, _translate("MainWindow", "轻柔缓解"))
        self.trm_mechine_workmode.setItemText(2, _translate("MainWindow", "持续缓解"))
        self.trm_mechine_workmode.setItemText(3, _translate("MainWindow", "强力缓解"))
        self.label_27.setText(_translate("MainWindow", "止痛药剂:"))
        self.trm_durg_use.setItemText(1, _translate("MainWindow", "酮铬酸"))
        self.trm_durg_use.setItemText(2, _translate("MainWindow", "氯诺昔康"))
        self.trm_durg_use.setItemText(3, _translate("MainWindow", "保泰松"))
        self.trm_durg_use.setItemText(4, _translate("MainWindow", "芬太尼"))
        self.trm_drug_speed.setPlaceholderText(_translate("MainWindow", "ml/s"))
        self.label_28.setText(_translate("MainWindow", "药剂流速:"))
        self.label_29.setText(_translate("MainWindow", "药剂用量:"))
        self.trm_drug_mass.setPlaceholderText(_translate("MainWindow", "ml"))
        self.trm_reset.setText(_translate("MainWindow", "重置"))
        self.trm_start.setText(_translate("MainWindow", "启动"))
import resource_interface
